spring.application.name=chem-lab-inventory
spring.profiles.active=local

spring.datasource.url=jdbc:mysql://localhost:3306/chem_lab_inventory
spring.datasource.username=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true